# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/
favicon: /images/avatar.jpg # 网站标签页的 icon
apple_touch_icon: /images/avatar.jpg # 用于苹果设备的 icon

title_join_string: " - " # 浏览器标签页中的标题分隔符，效果： 文章名 - 站点名
force_https: false # 强制所有链接升级为 HTTPS（适用于图片等资源出现 HTTP 混入报错）

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ""

# web_analytics:  # 网页访问统计
#   enable: false # 默认为false，启用网页统计改为true即可
#   baidu:  # 百度统计的Key，参见 https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 代码获取中 hm.js? 后边的字符串
#   google:  # Google统计的Tracking ID，参见 https://analytics.google.com/analytics/web/
#   tencent:  # 腾讯统计的H5 App id，参见 https://mta.qq.com/h5/manage/ctr_app_manage (开启高级功能才有cid)
#     sid:
#     cid:
#   woyaola:  # 51.la站点统计ID，参见 https://www.51.la/user/site/index
#   cnzz:  # 友盟/cnzz站点统计web_id，参见 https://web.umeng.com/main.php?c=site&a=show
#   leancloud:  # LeanCloud 计数统计，可用于 PV UV 展示，如果 web_analytics.enable 没有开启，PV UV 展示只会查询，不会增加
#     app_id:
#     app_key:
#     server_url:  # REST API 服务器地址，国际版不填

footer:
  statistics:
    enable: false
    source: "busuanzi" # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次" # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"
# banner_img: /img/bg/example.jpg   # 对应存放在 /source/img/bg/example.jpg

navbar:
  blog_title: "鱼鱼笑笑生" # 导航栏左侧的标题，为空则按 hexo config.title 显示
  ground_glass: # 导航栏毛玻璃特效，实验性功能，可能会造成页面滚动掉帧和抖动，部分浏览器不支持会自动不生效
    enable: false
    px: 0 # 模糊像素，只能为数字，数字越大模糊度越高
    alpha: 0 # 透明度，只能为数字，范围0~1，数字越大透明度越低，注意透明过度可能看不清菜单字体
  menu: # 可自行增减，key 用来关联 languages/*.yml，如不存在关联则显示 key 本身的值；icon 是 css class，可以省略；增加 name 可以强制显示指定名称
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    # - {
    #     key: 'category',
    #     link: '/categories/',
    #     icon: 'iconfont icon-category-fill',
    #   }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
    # - { key: "links", link: "/links/", icon: "iconfont icon-link-fill" } # 友链页，把前面#去掉即可展示
# 部署需要留意

# url: http://xxx.com/blog
# root: /blog/

code:
  copy_btn: true
  highlight:
    enable: true
    line_number: true
    lib: "highlightjs"
    highlightjs:
      style: "Obsidian"
      bg_color: true
    prismjs:
      style: "default"
      preprocess: true

#---------------------------
# 文章页
# Post Page
#---------------------------
post: # 部分配置同时控制自定义页面，注意备注
  # banner_img: /medias/banner/default.jpg
  # banner_img_height: 70 # available: 0 - 100
  #  banner_mask_alpha: 0.3 # available: 0 - 1.0
  meta: # 文章标题下方的信息
    date: # 文章日期
      enable: true
      format: "LL a" # 格式参照 ISO-8601 日期格式化，可参照 http://momentjs.cn/docs/#/parsing/string-format/
    wordcount: # 字数统计
      enable: true
      format: "{} 字" # 显示的文本，{}是数字的占位符（必须包含)，下同
    min2read: # 阅读时间
      enable: true
      format: "{} 分钟"
      words: 100 # 每分钟阅读多少字，如果是技术文章，建议降低
    views: # 阅读次数
      enable: false
      source: "busuanzi" # 统计数据来源，可选：busuanzi | leancloud，使用 leancloud 需要在 web_analytics 中设置 api 参数，使用 busuanzi 注意可能间歇抽风
      format: "{} 次"
  updated: # 在文章开头显示文章更新时间，该时间默认是 md 文件更新时间，可通过 front-matter 中 `updated` 手动指定（和 date 一样格式）
    enable: true
    content: 本文最后更新于： # 描述文字
    relative: false # 是否使用相对时间表示，比如："3 天前"
  toc: # 文章右侧目录
    enable: true
    headingSelector: h1,h2,h3,h4,h5,h6
    collapseDepth: 0 # 层级的折叠深度，0 是全部折叠，6 是全部不折叠
  copyright: # 版权声明
    enable: true
    content: '本博客所有文章除特别声明外，均采用 <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh" rel="nofollow noopener">CC BY-SA 4.0 协议</a> ，转载请注明出处！'
  prev_next: # 文章底部上一篇下一篇功能
    enable: true
  custom: # 文章底部自定义内容
    enable: false
    content: '<img src="https://octodex.github.com/images/jetpacktocat.png" class="rounded mx-auto d-block mt-5" style="width:150px; height:150px;">' # 自定义区域，支持 HTML，可自行插入赞赏码、公众号二维码等内容
  image_zoom: # 文章图片可点击放大
    enable: true # 开启后文章默认可用，自定义页面如需使用，需在 Front-matter 中指定 `image_zoom: true`，并且图片使用该格式插入：<img src="..." zoom />
  footnote: # 脚注语法，会在文章底部生成脚注，如果 Markdown 渲染器本身支持，则建议关闭，否则可能会冲突
    enable: true
    header: "" # 脚注的节标题，也可以在 front-matter 中通过 `footnote: <h2>Reference</h2>` 这种形式修改单页的节标题
  math: # 数学公式，开启之前需要更换 Markdown 渲染器，否则复杂公式会有兼容问题，具体请见：https://hexo.fluid-dev.com/docs/guide/##latex-数学公式
    enable: true # 开启后文章默认可用，自定义页面如需使用，需在 Front-matter 中指定 `math: true`
    specific: false # 开启后，只有在文章 Front-matter 里指定 `math: true` 才会在文章页启动公式转换，以便在页面不包含公式时提高加载速度
    engine: mathjax # 公式引擎  available: mathjax | katex
  mermaid: # 流程图，基于 mermaid-js，文档：http://mermaid-js.github.io/mermaid/
    enable: true # 开启后文章默认可用，自定义页面如需使用，需在 Front-matter 中指定 `mermaid: true`
    specific: true # 开启后，只有在文章 Front-matter 里指定 `mermaid: true` 才会在文章页启动公式转换，以便在页面不包含公式时提高加载速度
    options: { theme: "default" } # 接口选项，具体可见：http://mermaid-js.github.io/mermaid/#/mermaidAPI
  comments: # 评论
    enable: true # 开启评论
    type: giscus # 指定使用的评论模块  available: disqus | valine | gitalk | utterances | changyan | livere  推荐 utterances

giscus:
  src: "https://giscus.app/client.js"
  repo: "zhuiye/blog"
  repo-id: "R_kgDOJZqqIg"
  category: "Announcements"
  category-id: "DIC_kwDOJZqqIs4CftBl"
  mapping: "title"
  strict: "0"
  reactions-enabled: "1"
  emit-metadata: "0"
  input-position: "bottom"
  theme: "dark"
  lang: "zh-CN"
  crossorigin: "anonymous"
  async: true

index:
  banner_img: #/images/banner.jpg # 首页 Banner 头图，以下相同
  banner_img_height: 100 # 头图高度，屏幕百分比，available: 0 - 100
  banner_mask_alpha: 1 # 头图黑色蒙版的透明度，available: 0 - 1.0， 0 是完全透明（无蒙版），1 是完全不透明
  post_default_img: "" # 默认的文章封面图，当没有指定 index_img 时会使用该图片，若都为空则不显示任何图片
  slogan: # 首页副标题的独立设置
    enable: true # 为 false 不显示任何内容
    text: "我来问道无余说，云在青天水在瓶。" # 为空则按 hexo config.subtitle 显示
  auto_excerpt:
    enable: true
  post_url_target: _self # available: _blank | _self
  post_meta: # 是否显示文章信息（时间、分类、标签）
    date: true
    category: false
    tag: true

about: # 关于页需要手动创建，具体请见：https://hexo.fluid-dev.com/docs/guide/#%E5%85%B3%E4%BA%8E%E9%A1%B5
  banner_img: /images/banner.jpg
  banner_img_height: 60 # available: 0 - 100
  banner_mask_alpha: 1 # available: 0 - 1.0
  subtitle: "晨兴理荒秽，带月荷锄归。" # 打字机内容
  avatar: /images/avatar.jpg # 头像
  name: 鱼鱼笑笑生
  introduce: "兴趣使然的活着" # 支持 HTML
  icons: # 更多图标可从 https://hexo.fluid-dev.com/docs/icon/ 查找，class 代表图标的 css class
    - {
        class: "iconfont icon-github-fill",
        link: "https://github.com/zhuiye",
        tip: "github",
      }
    - { class: "iconfont rss icon-rss", link: "/atom.xml", tip: "rss" }
    - {
        class: "iconfont icon-envelope icon-mail",
        link: "503181017@qq.com",
        tip: "email",
      }
    # - {
    #     class: "iconfont twitter-fill icon-twitter-fill",
    #     link: "https://twitter.com/rxliuli",
    #     tip: "twitter",
    #   }

archive:
  banner_img: #/images/banner.jpg # 首页 Banner 头图，以下相同
  banner_img_height: 60 # 头图高度，屏幕百分比，available: 0 - 100
  banner_mask_alpha: 1 # 头图黑色蒙版的透明度，available: 0 - 1.0， 0 是完全透明（无蒙版），1 是完全不透明
  subtitle: "知识的匮乏，令人心生恐惧。" # 打字机内容

tag:
  banner_img: #/images/banner.jpg # 首页 Banner 头图，以下相同
  banner_img_height: 60 # 头图高度，屏幕百分比，available: 0 - 100
  banner_mask_alpha: 1 # 头图黑色蒙版的透明度，available: 0 - 1.0， 0 是完全透明（无蒙版），1 是完全不透明
  subtitle: "承认自己的无知，是开启智慧的大门。" # 打字机内容

